# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7154d83248aeae557122a009afd4fd541c1ed1595898d518d7d15db8793072202ebb94c43cae88d4a469676e9f28c60fb49f49f44e5898720807425bbc695a0b

test:
  secret_key_base: 9e037880900e3348a0919e2f878c2465b1dda1ee442474a80c8425de92a3a872995ce758e386762a6385671139f08bbb556378ad911faf3ed032feba7dadeb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
